package cz.palda97.lpclient.model.travelobjects

object LdConstants {
    const val GRAPH = "@graph"
    const val TYPE = "@type"
    const val ID = "@id"
    const val VALUE = "@value"

    const val VERSION = "http://etl.linkedpipes.com/ontology/version"
    const val PROFILE = "http://linkedpipes.com/ontology/profile"
    const val PREF_LABEL = "http://www.w3.org/2004/02/skos/core#prefLabel"
    const val CONFIGURATION_GRAPH = "http://linkedpipes.com/ontology/configurationGraph"
    const val TEMPLATE = "http://linkedpipes.com/ontology/template"
    const val X = "http://linkedpipes.com/ontology/x"
    const val Y = "http://linkedpipes.com/ontology/y"
    const val SOURCE_BINDING = "http://linkedpipes.com/ontology/sourceBinding"
    const val SOURCE_COMPONENT = "http://linkedpipes.com/ontology/sourceComponent"
    const val TARGET_BINDING = "http://linkedpipes.com/ontology/targetBinding"
    const val TARGET_COMPONENT = "http://linkedpipes.com/ontology/targetComponent"
    const val REPO_POLICY = "http://linkedpipes.com/ontology/rdfRepositoryPolicy"
    const val REPO_TYPE = "http://linkedpipes.com/ontology/rdfRepositoryType"
    const val DESCRIPTION = "http://purl.org/dc/terms/description"
    const val ORDER = "http://linkedpipes.com/ontology/order"
    const val VERTEX = "http://linkedpipes.com/ontology/vertex"
    const val BINDING = "http://linkedpipes.com/ontology/binding"
    const val TAG = "http://etl.linkedpipes.com/ontology/tag"

    const val TYPE_PIPELINE = "http://linkedpipes.com/ontology/Pipeline"
    const val TYPE_COMPONENT = "http://linkedpipes.com/ontology/Component"
    const val TYPE_CONNECTION = "http://linkedpipes.com/ontology/Connection"
    const val TYPE_EXECUTION_PROFILE = "http://linkedpipes.com/ontology/ExecutionProfile"
    const val TYPE_EXECUTION = "http://etl.linkedpipes.com/ontology/Execution"
    const val TYPE_TOMBSTONE = "http://linkedpipes.com/ontology/Tombstone"
    const val TYPE_VERTEX = "http://linkedpipes.com/ontology/Vertex"
    const val TYPE_TEMPLATE = "http://linkedpipes.com/ontology/Template"
    const val TYPE_RUNTIME_CONFIGURATION = "http://linkedpipes.com/ontology/RuntimeConfiguration"
    const val TYPE_PORT_INPUT = "http://linkedpipes.com/ontology/Input"
    const val TYPE_PORT_OUTPUT = "http://linkedpipes.com/ontology/Output"
    const val TYPE_TEMPLATE_JAR = "http://linkedpipes.com/ontology/JarTemplate"
    const val TYPE_METADATA = "http://etl.linkedpipes.com/ontology/Metadata"

    const val COMPONENT_EXECUTED = "http://etl.linkedpipes.com/ontology/execution/componentExecuted"
    const val COMPONENT_FINISHED = "http://etl.linkedpipes.com/ontology/execution/componentFinished"
    const val COMPONENT_MAPPED = "http://etl.linkedpipes.com/ontology/execution/componentMapped"
    const val COMPONENT_TO_EXECUTE = "http://etl.linkedpipes.com/ontology/execution/componentToExecute"
    const val COMPONENT_TO_MAP = "http://etl.linkedpipes.com/ontology/execution/componentToMap"
    const val EXECUTION_END = "http://etl.linkedpipes.com/ontology/execution/end"
    const val EXECUTION_SIZE = "http://etl.linkedpipes.com/ontology/execution/size"
    const val EXECUTION_START = "http://etl.linkedpipes.com/ontology/execution/start"
    const val EXECUTION_PIPELINE = "http://etl.linkedpipes.com/ontology/pipeline"
    const val EXECUTION_STATUS = "http://etl.linkedpipes.com/ontology/status"

    const val EXECUTION_STATUS_FINISHED = "http://etl.linkedpipes.com/resources/status/finished"
    const val EXECUTION_STATUS_FAILED = "http://etl.linkedpipes.com/resources/status/failed"
    const val EXECUTION_STATUS_RUNNING = "http://etl.linkedpipes.com/resources/status/running"
    const val EXECUTION_STATUS_CANCELLED = "http://etl.linkedpipes.com/resources/status/cancelled"
    const val EXECUTION_STATUS_DANGLING = "http://etl.linkedpipes.com/resources/status/dangling"
    const val EXECUTION_STATUS_CANCELLING = "http://etl.linkedpipes.com/resources/status/cancelling"
    const val EXECUTION_STATUS_QUEUED = "http://etl.linkedpipes.com/resources/status/queued"
    const val EXECUTION_STATUS_MAPPED = "http://etl.linkedpipes.com/resources/status/mapped"

    const val SCHEMA_INT = "http://www.w3.org/2001/XMLSchema#int"
    const val SCHEMA_INTEGER = "http://www.w3.org/2001/XMLSchema#integer"

    const val SAME_AS = "http://www.w3.org/2002/07/owl#sameAs"
    const val MAPPING = "http://etl.linkedpipes.com/resources/plugins/mapping"

    const val INHERITANCE_NONE = "http://plugins.linkedpipes.com/resource/configuration/None"
    const val INHERITANCE_INHERIT = "http://plugins.linkedpipes.com/resource/configuration/Inherit"

    const val SERVER_TIME = "http://etl.linkedpipes.com/ontology/serverTime"
}